name = "tom"
version = "0.2.0"

description = "A pure Gleam TOML parser!"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "toml" }
links = [{ title = "TOML website", href = "https://toml.io/en/" }]

[dependencies]
gleam_stdlib = "~> 0.32"

[dev-dependencies]
gleeunit = "~> 1.0"
